{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pizza_user_count_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_system_memory_used{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_system_cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_auth_success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(pizza_auth_fail_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizza_purchase_error_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(pizza_purchase_revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Bitcoin"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizza_http_latency_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "HTTP Requests/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizza_http_request_all{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(pizza_http_request_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(pizza_http_request_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Post"
    },
    {
     "expr": "rate(pizza_http_request_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(pizza_http_request_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Put"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pizza_purchase_latency_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Latency"
    }
   ]
  }
 ]
}